### ISSUE TITLE
items returned to the pool multiple times

### ISSUE THREAD

**Issue by osi** [reactor/reactor-pool#101]
I originally reported this as r2dbc/r2dbc-pool#92, but was recommended to take it here. (the following test is an abbreviated from of what's there)

Initially observed on R2DBC Arabba-SR6, still present on Arabba-SR7. 
 - target is PostgreSQL 12 (AWS RDS). 
 - openjdk version "11.0.7.0.101" 2020-07-14 LTS (Zulu)

A given `PostgresqlConnection` is being provided to multiple pool users simultaneously.

With Arabba-SR7, I started seeing the following stack trace (there was no exception from the pool thrown with SR6

```
java.lang.IllegalArgumentException: Too many permits returned: returned=1, would bring to 11/10
  at reactor.pool.AllocationStrategies$SizeBasedAllocationStrategy.returnPermits(AllocationStrategies.java:141)
  at reactor.pool.AbstractPool.destroyPoolable(AbstractPool.java:147)
  at reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:310)
  at reactor.pool.SimpleDequePool.drain(SimpleDequePool.java:204)
  at reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:199)
  at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:378)
  at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:130)
```

I have also [added logging](https://gist.github.com/osi/99d1263e67021f898a89d66417aa3fa5) around the acquisition and close of connections, both on over and under the pool. My logging shows this:
```
2020-10-01 22:23:03.844 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 41', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:03.851 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 41', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
2020-10-01 22:23:17.116 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 51', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:17.166 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 51', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
2020-10-01 22:23:17.179 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 62', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:17.225 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 70', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:19.297 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 62', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
2020-10-01 22:23:19.302 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 70', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
```

`under pool 4` is the database connection `over pool 41` and `over pool 51` both acquire and release it as expected however, then `over pool 62` and `over pool 70` are provided the same underlying database connection simultaneously.

I am unable to reproduce this in my test suite; this does consistently happen when running my application in a deployed environment.

There doesn't seem to be any additional logging I can enable in either `r2dbc-pool` or `reactor-pool` to help debug. I've temporarily disabled `r2dbc-pool` in my application, and several observed "weird problems" have now gone away. 

I'm open on how to debug this further.

**Comment by osi** [comment]
I've re-tested this against `Arraba-SR8`, and then both reactor-pool `0.1.7-RELEASE` and `0.2.0` and I can still provoke a failure.

I can reliably have it fail as part of my test suite. I've been unsuccessful in trying to pare down the test to something small though.

**Comment by osi** [comment]
I'm not 100% certain that the exhibited problem is a value being put into the `idleResources` multiple times. I created a [monitor](https://gist.github.com/osi/919ac5047d4520c2aab4eeba90606cde) of that field, and I'm not seeing a value > 1, even in the scenario where I detect a resource being used twice. 

I'm seeing > 100ms between an acquire and a "duplicate" acquire (with plenty of other non-problematic acquires in-between).

It makes me wonder if the problem is a resource is being handed out, but not removed from `idleResources`, allowing it to be used twice.

**Comment by osi** [comment]
After digging further I'm not certain that this is a `reactor-pool` problem. It seems like there is some interplay between how `r2dbc-pool` will release a resource when the create mono is canceled and using the resource in a `usingWhen` block. Still digging.

**Comment by osi** [comment]
With r2dbc `Arraba-SR7`, I was reliably seeing a race to release a connection due to how the ConnectionPool will [try and release on a cancel signal](https://github.com/r2dbc/r2dbc-pool/blob/b16b8aad71bbe78c55943e66278df4758d8cb538/src/main/java/io/r2dbc/pool/ConnectionPool.java#L114-L119), as well as due to `Connection.close` being called. With `Arraba-SR8`, I'm not longer seeing that occur. It's possible that this was exposing a race that was present in `reactor-pool`, but I've been unable to conclusively determine that. 

As it _seems_ that SR8 alleviates the issue, I'm going to run with that a bit to verify.

**Comment by simonbasle** [comment]
@osi thanks for the investigation so far. One month after switching to `Arraba-SR8`, has the issue reproduced at all?

**Comment by osi** [comment]
@simonbasle the issue hasn't happened since switching to `Arraba-SR8`

**Comment by simonbasle** [comment]
Great to hear, closing this then 👍
